cors/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hashflix.urls', namespace='filme')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hashflix/urls.py
from django.urls import path
from .views import Home, HomeFilmes, DetalhesFilmes

app_name = 'filme'

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('filmes/', HomeFilmes.as_view(), name="homefilmes"),
    path('filmes/<int:pk>', DetalhesFilmes.as_view(), name="detalhesfilme"),
]

hashflix/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

LISTA_CATEGORIAS = (
    ("ANALISE", "Análise"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros"),
)

# criar filmes
class Filme(models.Model):
    thumb = models.ImageField(upload_to='thumb_filmes') # Upload dos filmes nesta pasta criada chamada 'thumb_filmes'
    titulo = models.CharField(max_length=100, null=True)
    descricao = models.TextField(blank=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS) # Dois argumentos o tamanho e a lista que tem o choises, além disso, precisamos criar a lista de categorias
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo
    
    
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100, null=True)
    video = models.URLField()
 
    def __str__(self):
        return  self.filme.titulo + " - " + self.titulo
    

hashflix/views.py
from django.shortcuts import render
from .models import Filme
from django.views.generic import TemplateView, ListView, DetailView

# Functions Class Base Views -> Sites complexos, tendo templates prontos OU Functions Class View -> Sites simples, não vem com templates prontos

# Create your views here.
# def Home(request):
#    return render(request, 'hashflix/pages/home.html')


class Home(TemplateView):
    template_name = 'hashflix/pages/home.html'
 

# def HomeFilme(request):
#    context = {}
#    lista_filmes = Filme.objects.all()
#    context['lista_filmes'] = lista_filmes
#    return render(request, 'hashflix/pages/homefilmes2.html', context)

class HomeFilmes(ListView):
    template_name = 'hashflix/pages/homefilmes2.html'
    model = Filme # object.list

class DetalhesFilmes(DetailView):
    template_name = 'hashflix/pages/detalhesfilmes.html'
    model = Filme

hashflix/templates/hashflix/pages/detalhesfilmes.html
{% extends 'global/base.html' %}

{% block title %} Hashflix |  {% endblock title %}

{% block content %}

    <h1>Essa é o detalhe do filme: {{ object.titulo }}</h1>
    <p>{{ object }}</p>
    <p>{{ object.descricao }}</p>
    <img src="{{object.thumb.url}}" >

{% endblock content %}

hashflix/templates/hashflix/pages/home.html
{% extends 'global/base.html' %}

{% block title %} Hashflix | {% endblock title %}

{% block content %}

    {% include 'hashflix/partials/banner.html' %}
    {% include 'hashflix/partials/topic.html' %}

{% endblock content %}

hashflix/templates/hashflix/pages/homefilmes2.html
{% extends 'global/base.html' %}

{% block title %} Hashflix | homefilmes {% endblock title %} 

{% block content %}

    {% include 'hashflix/partials/homefilmes.html' %}

    {% for filmes in object_list %}
    <a href="{% url 'filme:detalhesfilme' filmes.id %}"><p class="lista">{{ filmes.titulo }}</p></a> 
    <p class="lista">{{ filmes.descricao }}</p> 
    <img src="{{ filmes.thumb.url }}" /> 
    {% endfor %}


{% endblock content %}

hashflix/templates/hashflix/partials/banner.html
{% load static %}

<div class="div-content-box">

    <div>
        <div>
            <h1>Filmes, séries e muito mais.</h1>
            <h1>Sem limites.</h1>
            <p>Assista onde quiser. Cancele quando quiser.</p>
        </div>
        <div>
           <p>Quer assister? informe seu email para criar ou reiniciar sua assinatura.</p>
            <label for="text">
                <input type="text" id="text" placeholder="Email" name="text"/><a href="#">Vamos lá<ion-icon name="chevron-forward-outline"></ion-icon></a>
            </label>
        </div>
    </div>

</div>

hashflix/templates/hashflix/partials/head/head.html
{% load static %}

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <link rel="stylesheet" href="{% static 'hashflix/css/style.css' %}"/>

</head>

hashflix/templates/hashflix/partials/homefilmes.html
{% load static %}

<h1>Lista filmes</h1>

hashflix/templates/hashflix/partials/topic.html
{% load static %}

<section class="section-content-box">

    <div>
        <div>
            <div>
               <h1>Aproveite TV</h1>
               <p>Assista em Smart TVs, PlayStation, Xbox, Chromecast, Apple TV, aparelhos de Blu-ray e outros dispositivos.</p>
            </div>
            <div>
                <img src="{% static 'hashflix/img/tv.png' %}" alt="">
            </div>
        </div>
        <div>
            <div>
                <img src="{% static 'hashflix/img/mobile-0819.jpg' %}" alt="">
            </div>
            <div>
                <h1>Assista quando quiser.</h1>
                <p>Assista no celular, tablet, Smart TV ou notebook sem pagar a mais por isso.</p>
             </div>
        </div>
        <div>
            <div>
                <h1>Crie perfis para crianças.</h1>
                <p>Deixe as crianças se aventurarem com seus personagens favoritos em um espaço feito só para elas, sem pagar a mais por isso.</p>
            </div>
            <div>
                <img src="{% static 'hashflix/img/netflix_kid.png' %}" alt="">
            </div>
        </div>
    </div>

</section>